# Generated by Django 4.1.2 on 2023-02-25 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=100)),
                ('Phone', models.IntegerField()),
                ('Location', models.CharField(max_length=500)),
                ('Message', models.TextField()),
            ],
            options={
                'db_table': 'Register',
            },
        ),
        migrations.CreateModel(
            name='SignupInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=100)),
                ('Password', models.CharField(max_length=50)),
                ('Mobile', models.IntegerField()),
            ],
            options={
                'db_table': 'Signup',
            },
        ),
        migrations.CreateModel(
            name='WorkoutCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cat_Image', models.ImageField(upload_to='')),
                ('Cat_Logo', models.ImageField(upload_to='')),
                ('Cat_Name', models.CharField(max_length=100)),
                ('Cat_Description', models.TextField()),
            ],
        ),
    ]
