# Generated by Django 4.1.2 on 2023-03-11 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Packages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Duration', models.CharField(max_length=25)),
                ('Price', models.IntegerField(default=0)),
                ('Include', models.TextField()),
            ],
            options={
                'db_table': 'Packages',
            },
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=100)),
                ('Phone', models.IntegerField()),
                ('Location', models.CharField(max_length=500)),
                ('Message', models.TextField()),
            ],
            options={
                'db_table': 'Register',
            },
        ),
        migrations.CreateModel(
            name='SignupInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=100)),
                ('Password', models.CharField(max_length=50)),
                ('Mobile', models.IntegerField()),
            ],
            options={
                'db_table': 'Signup',
            },
        ),
        migrations.CreateModel(
            name='WorkoutCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cat_Image', models.ImageField(upload_to='')),
                ('Cat_Logo', models.ImageField(upload_to='')),
                ('Cat_Name', models.CharField(max_length=100)),
                ('Cat_Description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutSubcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='')),
                ('Lifting_Name', models.CharField(max_length=50)),
                ('Description', models.TextField()),
                ('Category', models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='Adminapp.workoutcategory')),
            ],
            options={
                'db_table': 'WorkoutSubcategory',
            },
        ),
        migrations.CreateModel(
            name='WorkoutExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='')),
                ('Exer_Name', models.CharField(max_length=50)),
                ('Description', models.TextField()),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Adminapp.workoutcategory')),
            ],
            options={
                'db_table': 'WorkoutExercise',
            },
        ),
    ]
