# Generated by Django 4.1.2 on 2023-03-11 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutexercise',
            name='Info',
            field=models.TextField(default='abc'),
        ),
        migrations.AddField(
            model_name='workoutexercise',
            name='Name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
