# Generated by Django 4.1.2 on 2023-03-11 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Adminapp', '0002_workoutexercise_info_workoutexercise_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workoutexercise',
            name='Info',
        ),
        migrations.RemoveField(
            model_name='workoutexercise',
            name='Name',
        ),
    ]
