# Generated by Django 4.1.2 on 2023-03-02 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Adminapp', '0002_workoutsubcategory'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WorkoutSubcategory',
            new_name='WorkoutExercise',
        ),
        migrations.AlterModelTable(
            name='workoutexercise',
            table='WorkoutExercise',
        ),
    ]
