# Generated by Django 4.1.2 on 2023-03-02 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminapp', '0003_rename_workoutsubcategory_workoutexercise_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutSubcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='')),
                ('Lifting_Name', models.CharField(max_length=50)),
                ('Description', models.TextField()),
            ],
            options={
                'db_table': 'WorkoutSubcategory',
            },
        ),
    ]
