# Generated by Django 4.1.2 on 2023-03-11 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Adminapp', '0003_remove_workoutexercise_info_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exec_Sub_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Description', models.TextField()),
                ('Subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Adminapp.workoutsubcategory')),
            ],
            options={
                'db_table': 'Exec_Sub_Info',
            },
        ),
    ]
