# Generated by Django 4.1.2 on 2023-03-11 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Adminapp', '0004_exec_sub_info'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workoutsubcategory',
            old_name='Lifting_Name',
            new_name='Sub_Name',
        ),
    ]
