# Generated by Django 4.1.2 on 2023-03-02 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Adminapp', '0004_workoutsubcategory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workoutexercise',
            old_name='Lifting_Name',
            new_name='Exer_Name',
        ),
    ]
