# Generated by Django 4.1.2 on 2023-03-08 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminapp', '0005_rename_lifting_name_workoutexercise_exer_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Packages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Duration', models.CharField(max_length=25)),
                ('Price', models.FloatField(default=0)),
                ('Include', models.TextField()),
            ],
            options={
                'db_table': 'Packages',
            },
        ),
    ]
