# Generated by Django 4.1.2 on 2023-03-11 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Adminapp', '0005_rename_lifting_name_workoutsubcategory_sub_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='')),
                ('Exer_Name', models.CharField(max_length=50)),
                ('Description', models.TextField()),
                ('Subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Adminapp.workoutsubcategory')),
            ],
            options={
                'db_table': 'SubExercise',
            },
        ),
        migrations.DeleteModel(
            name='WorkoutExercise',
        ),
    ]
