# Generated by Django 4.1.2 on 2023-03-08 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminapp', '0006_packages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packages',
            name='Price',
            field=models.IntegerField(default=0),
        ),
    ]
