# Generated by Django 4.1.2 on 2023-03-14 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminapp', '0007_catexercise'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Work', models.CharField(max_length=50)),
                ('Weight', models.CharField(max_length=10)),
                ('Height', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254)),
                ('Contact', models.IntegerField()),
                ('Address', models.TextField()),
                ('Specialities', models.TextField()),
                ('Qualification', models.TextField()),
                ('Achievement', models.TextField()),
                ('Description', models.TextField()),
            ],
            options={
                'db_table': 'Trainer',
            },
        ),
    ]
