# Generated by Django 4.1.2 on 2023-03-14 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminapp', '0008_trainer'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='Image',
            field=models.ImageField(default='abc.jpg', upload_to=''),
            preserve_default=False,
        ),
    ]
